@extends('layout')
@section('title','Okesheni · Professional event invitation and RSVP management')
@section('content')
<main class="corporate-landing">
    <section class="corp-hero"><div class="wrap corp-hero-grid">
        <div class="corp-hero-copy reveal"><span class="eyebrow">Corporate event operations, simplified</span><h1>Every guest informed.<br>Every response accounted for.</h1><p class="hero-lead">Okesheni gives professional teams one place to create branded invitations, coordinate multi-channel outreach, and track RSVPs from first send to final attendance list.</p><div class="actions"><a class="btn" href="/register">Start managing events ↗</a><a class="btn secondary" href="#product">Explore the platform</a></div><div class="hero-proof"><span>Branded communications</span><span>Private RSVP links</span><span>Live response tracking</span></div></div>
        <div class="event-slider reveal" data-slider aria-label="Professional event highlights"><div class="event-slides"><figure class="event-slide is-active"><img src="/assets/images/conference.png" alt="A keynote speaker addressing a professional conference"><figcaption><span>01</span><strong>Conferences that command attention</strong></figcaption></figure><figure class="event-slide"><img src="/assets/images/networking.png" alt="Business leaders networking at a formal event"><figcaption><span>02</span><strong>Connections that move business forward</strong></figcaption></figure><figure class="event-slide"><img src="/assets/images/award.png" alt="An award being presented at a corporate gala"><figcaption><span>03</span><strong>Recognition moments worth remembering</strong></figcaption></figure></div><div class="slider-controls"><button type="button" data-prev aria-label="Previous image">←</button><div class="slider-dots"><button type="button" class="is-active" data-slide="0" aria-label="Show conference image"></button><button type="button" data-slide="1" aria-label="Show networking image"></button><button type="button" data-slide="2" aria-label="Show award image"></button></div><button type="button" data-next aria-label="Next image">→</button></div><div class="slider-stat"><b>One platform</b><span>Invitation to attendance</span></div></div>
    </div></section>
    <section class="corp-strip"><div class="wrap"><span>BUILT FOR</span><strong>Executive forums</strong><strong>Conferences</strong><strong>Stakeholder meetings</strong><strong>Corporate galas</strong><strong>Private launches</strong></div></section>
    <section class="wrap platform-infographic reveal" aria-label="Okesheni platform overview"><div><strong>3</strong><span>Integrated delivery channels</span></div><i></i><div><strong>1</strong><span>Live organizer dashboard</span></div><i></i><div><strong>100%</strong><span>Personalized RSVP links</span></div><i></i><div><strong>4</strong><span>Steps from setup to ready</span></div></section>
    <section id="product" class="wrap corp-section"><div class="section-intro reveal"><span class="eyebrow">One event command centre</span><h2>Professional communication without the operational clutter.</h2><p>Replace disconnected spreadsheets, message threads, and manual follow-ups with one clear workflow your team can run confidently.</p></div><div class="corp-feature-grid"><article class="corp-feature featured"><span class="feature-number">01</span><h3>Build on-brand invitations</h3><p>Add your organization’s logo, select invitation colors, customize the message, and attach a professionally designed PDF or PNG card.</p><div class="palette-sample"><i></i><i></i><i></i><span>Your brand, consistently presented.</span></div></article><article class="corp-feature"><span class="feature-number">02</span><h3>Reach guests on the right channel</h3><p>Send or resend selected invitations through email, SMS, or WhatsApp while preserving each guest’s private confirmation link.</p></article><article class="corp-feature"><span class="feature-number">03</span><h3>Turn responses into decisions</h3><p>Monitor confirmations, declines, seat counts, and dietary requirements from a single event dashboard.</p></article></div></section>
    <section id="how" class="corp-process"><div class="wrap"><div class="section-intro light reveal"><span class="eyebrow">A controlled workflow</span><h2>From guest list to event-ready.</h2></div><div class="process-grid"><article><span>01</span><h3>Configure</h3><p>Create the event, set the RSVP deadline, and tailor the invitation to your brand.</p></article><article><span>02</span><h3>Import</h3><p>Upload your Excel or CSV guest list, or add individual guests directly.</p></article><article><span>03</span><h3>Communicate</h3><p>Select recipients and send personalized invitations across your preferred channels.</p></article><article><span>04</span><h3>Coordinate</h3><p>Track attendance and export an accurate response list for your event team.</p></article></div></div></section>
    <section class="wrap visual-story reveal"><div class="visual-story-image"><img src="/assets/images/networking.png" alt="Professionals connecting during an event"><span>Meaningful connections</span></div><div><span class="eyebrow">Designed around the guest journey</span><h2>From the first message to the final handshake.</h2><p>Okesheni keeps communication consistent and response data useful, so organizers can focus on the experience in the room.</p><div class="journey-flow"><span>Invite</span><i>→</i><span>Confirm</span><i>→</i><span>Attend</span><i>→</i><span>Connect</span></div></div></section>
    <section class="wrap corp-section channel-section"><div class="reveal"><span class="eyebrow">Designed for guest confidence</span><h2>A clear invitation. A simple response.</h2><p>Every guest receives a personal RSVP link with the essential event details, attendance choices, guest limits, and dietary information—optimized for desktop and mobile.</p><ul class="check-list"><li>Unique, private response links</li><li>Custom email and SMS messaging</li><li>Controlled guest and seat limits</li><li>Immediate organizer visibility</li></ul></div><div class="channel-card reveal"><span class="eyebrow">Multi-channel delivery</span><div><b>EMAIL</b><p>Branded HTML invitations with optional PDF or PNG attachments.</p></div><div><b>SMS</b><p>Concise custom templates with a protected RSVP link.</p></div><div><b>WHATSAPP</b><p>Approved template delivery for direct guest communication.</p></div></div></section>
    <section id="clients" class="client-section"><div class="wrap"><div class="section-intro reveal"><span class="eyebrow">Clients</span><h2>Built for teams responsible for the guest experience.</h2><p>Okesheni supports organizations coordinating high-value events where accuracy, presentation, and timely responses matter.</p></div><div class="audience-grid"><div><span>01</span><strong>Corporate teams</strong><p>Leadership forums, launches, annual events, and stakeholder gatherings.</p></div><div><span>02</span><strong>Foundations & institutions</strong><p>Fundraisers, donor events, ceremonies, and community programs.</p></div><div><span>03</span><strong>Event professionals</strong><p>Agencies and planners managing invitations on behalf of their clients.</p></div><div><span>04</span><strong>Hospitality teams</strong><p>Venues coordinating guest-ready experiences with organizers.</p></div></div></div></section>
    <section id="partners" class="wrap partner-section"><div class="partner-copy reveal"><span class="eyebrow">Partners</span><h2>Better events are built together.</h2><p>We work alongside event agencies, venues, hospitality providers, communications teams, and technology partners to deliver a coordinated guest journey.</p><a class="btn secondary" href="mailto:{{ config('mail.from.address') }}">Partner with Okesheni ↗</a></div><div class="partner-types reveal"><span>Event agencies</span><span>Venues</span><span>Hospitality</span><span>Communications</span><span>Technology</span><span>Production teams</span></div></section>
    <section class="image-break reveal"><img src="/assets/images/award.png" alt="An award presented during a professional gala"><div><img src="/assets/logo/logo_vertical.png" alt="Okesheni"><span class="eyebrow">Moments, professionally managed</span><h2>Make the experience feel effortless.</h2></div></section>
    <section class="corp-cta"><div class="reveal"><span class="eyebrow">Run your next event with clarity</span><h2>A professional experience for your team and every guest.</h2><p>Set up your event, bring your guest list, and manage every response from one secure workspace.</p><a class="btn" href="/register">Create your event ↗</a></div></section>
</main>
<script>
    (function () {
        const slider = document.querySelector('[data-slider]');
        if (slider) {
            const slides = [...slider.querySelectorAll('.event-slide')], dots = [...slider.querySelectorAll('[data-slide]')]; let current = 0;
            const show = function (index) { current = (index + slides.length) % slides.length; slides.forEach((slide, i) => slide.classList.toggle('is-active', i === current)); dots.forEach((dot, i) => dot.classList.toggle('is-active', i === current)); };
            slider.querySelector('[data-prev]').addEventListener('click', function () { show(current - 1); }); slider.querySelector('[data-next]').addEventListener('click', function () { show(current + 1); }); dots.forEach(function (dot) { dot.addEventListener('click', function () { show(Number(dot.dataset.slide)); }); });
            if (!window.matchMedia('(prefers-reduced-motion: reduce)').matches) window.setInterval(function () { show(current + 1); }, 5500);
        }
        if ('IntersectionObserver' in window) { const observer = new IntersectionObserver(function (entries) { entries.forEach(function (entry) { if (entry.isIntersecting) entry.target.classList.add('is-visible'); }); }, { threshold: .12 }); document.querySelectorAll('.reveal,.corp-feature,.process-grid article,.audience-grid>div').forEach(function (element) { element.classList.add('reveal'); observer.observe(element); }); } else document.querySelectorAll('.reveal').forEach(function (element) { element.classList.add('is-visible'); });
    }());
</script>
@endsection
